{
 "title": "New dashboard",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Maximum number of drifted columns per day:",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE(timestamp) as date,\r\n  MAX(num_drifted_columns) as max_drifted_columns\r\nFROM\r\n  dummy_metrics\r\nGROUP BY\r\n  DATE(timestamp)\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Correlation between prediction drift and share of missing values:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp as time,\r\n  prediction_drift,\r\n  share_missing_values\r\nFROM\r\n  dummy_metrics\r\nORDER BY\r\n  timestamp"
    }
   ]
  },
  {
   "title": "Time series of prediction drift:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp as time,\r\n  prediction_drift\r\nFROM\r\n  dummy_metrics\r\nORDER BY\r\n  timestamp"
    }
   ]
  }
 ]
}